### ISSUE TITLE
Error: Could not find or load main class com.stastnarodina.workflowVisualiser.Main

### ISSUE THREAD

**Issue by RCS-Owner** [jstastny/rtc-workflow-visualiser#2]
I originally thought this was an issue with the Scrum template because the first run was with the original visualiser.jar and generated the same error as a user that had posted on the original blog back in 2011. However, I downloaded the 2014 release and ran it with a different error leading me to believe there is something else going on.

I did find an issue with Graphviz that would not allow for any spaces or special characters in the path so I ended up installing to an Applications folder directly on the C drive. I did the same with the location for the visualiser and got the error listed in the subject line when attempting to run. Below is the path and command used to run it.

`C:\Applications\RTC-Workflow-Visualizer>java -jar "C:\Applications\RTC-Workflow-Visualizer\workflow-visualiser-0.0.3-jar-with-dependencies.jar" -o "C:\Applications\RTC-Workflow-Visualizer" -d "C:\Applications\Graphviz2.38\bin\dot.exe" scrum-template-05-25-2017.xml`
_Error: Could not find or load main class com.stastnarodina.workflowVisualiser.Main_

**When I attempted to use the original visualiser.jar file I got the following errors:**
`C:\Applications\RTC-Workflow-Visualizer>java -jar "C:\Applications\RTC-Workflow-Visualizer\visualiser.jar" -o "C:\Applications\RTC-Workflow-Visualizer" -d "C:\Applications\Graphviz2.38\bin\dot.exe" scrum-template-05-25-2017.xml`
_com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanComment(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanComment(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
        at com.stastnarodina.workflowVisualiser.Parser.parse(Parser.java:32)
        at com.stastnarodina.workflowVisualiser.Main.main(Main.java:46)_

**Comment by jstastny** [comment]
Hello,

thanks for reporting.

It still does not stop to surprise me that people still actually use this script.

Anyways, the classpath issue (`Error: Could not find or load main class com.stastnarodina.workflowVisualiser.Main`) should be fixed in #3. I merged it and prepared version 0.0.4, which contains the fix: https://github.com/jstastny/rtc-workflow-visualiser/releases/tag/workflow-visualiser-0.0.4

**Comment by jstastny** [comment]
I hope that the issue you describe regarding encoding was fixed by @gabarmas-ibm in #1, which is also part of 0.0.4. Can you, please, re-test and see if this helps?

**Comment by jstastny** [comment]
I believe both issues mentioned should be resolved in 0.0.4 so closing this now.
Feel free to reopen in case it still does not work for you.

**Comment by RCS-Owner** [comment]
Hey Jan,

First off, when you create something so useful and it continues to be useful across multiple versions of the application, I would be surprised if people weren't using it to help update documentation and deliverables. I know I really can't thank you enough for this!

Thanks for the quick turn-around! The workflow-visualiser-0.0.4-jar-with-dependencies.jar worked perfectly. I did try running the workflow-visualiser-0.0.4.jar and thought you might want to be aware that I got the following result:

> no main manifest attribute, in workflow-visualiser-0.0.4.jar

Thanks again!

All the best,

-michael

**Comment by jstastny** [comment]
Awesome. Glad it worked for your.

The fact that the `workflow-visualiser-0.0.4.jar` does not have the `main` attribute in manifest is expected. However, given that the tool is expected to be run as "script", providing jar without main class and without dependencies is probably not useful and likely misleading. I will remove it.

Best,
Jan
